export const emptyTableData = [
    {
        period: "Period 1",
        nursery: "English",
        lkg: ["Maths"],
        ukg: ["Science"],
        grade1: ["English"],
        grade2: ["Nepali"],
        grade3: ["Social Studies"],
        grade4: ["Library"],
        grade5: ["Computer Lab"],
        grade6: ["Maths"],
        grade7: ["English"],
        grade8: ["Vocational Training"],
        grade9: ["Physics"],
        grade10: ["Chemistry"],
    },
    {
        period: "Period 2",
        nursery: "Drawing",
        lkg: ["Storytelling"],
        ukg: ["Music"],
        grade1: ["Maths"],
        grade2: ["Science"],
        grade3: ["English"],
        grade4: ["Nepali"],
        grade5: ["PT"],
        grade6: ["Library"],
        grade7: ["Maths"],
        grade8: ["Biology Lab"],
        grade9: ["Computer Lab"],
        grade10: ["Social Studies"],
    },
    {
        period: "Period 3",
        nursery: "PT",
        lkg: ["Rhymes"],
        ukg: ["Drawing"],
        grade1: ["Nepali"],
        grade2: ["Library"],
        grade3: ["Science"],
        grade4: ["Vocational Training"],
        grade5: ["Maths"],
        grade6: ["Computer Lab"],
        grade7: ["Science"],
        grade8: ["English"],
        grade9: ["Maths"],
        grade10: ["Physics Lab"],
    },
    {
        period: "Period 4",
        nursery: "Nap Time",
        lkg: ["Music"],
        ukg: ["PT"],
        grade1: ["Drawing"],
        grade2: ["English"],
        grade3: ["Maths"],
        grade4: ["Science"],
        grade5: ["Nepali"],
        grade6: ["Library"],
        grade7: ["Vocational Training"],
        grade8: ["Social Studies"],
        grade9: ["Chemistry"],
        grade10: ["Computer Lab"],
    },
    {
        period: "Period 5",
        nursery: "Storytelling",
        lkg: ["Free Play"],
        ukg: ["Drawing"],
        grade1: ["Music"],
        grade2: ["Computer"],
        grade3: ["Library"],
        grade4: ["PT"],
        grade5: ["Social Studies"],
        grade6: ["Biology"],
        grade7: ["English"],
        grade8: ["Nepali"],
        grade9: ["Physics"],
        grade10: ["Vocational Training"],
    },
    {
        period: "Period 6",
        nursery: "Rhymes",
        lkg: ["Nap Time"],
        ukg: ["English"],
        grade1: ["Library"],
        grade2: ["PT"],
        grade3: ["Vocational Training"],
        grade4: ["Science"],
        grade5: ["Maths"],
        grade6: ["Nepali"],
        grade7: ["Computer Lab"],
        grade8: ["Chemistry"],
        grade9: ["Social Studies"],
        grade10: ["Physics Lab"],
    },
    {
        period: "Period 7",
        nursery: "Free Play",
        lkg: ["PT"],
        ukg: ["Games"],
        grade1: ["Storytelling"],
        grade2: ["Drawing"],
        grade3: ["Music"],
        grade4: ["English"],
        grade5: ["Computer"],
        grade6: ["Library"],
        grade7: ["Science"],
        grade8: ["Physics"],
        grade9: ["Vocational Training"],
        grade10: ["Nepali"],
    },
];
